# Tinythreads Catalogue Configuration
# Auto-play interval for product tile carousels (in milliseconds)
autoPlayInterval=3000

# Enable pagination dots for carousels
enableDotPagination=true

# Enable infinite loop for carousels
autoPlayInfiniteLoop=true

# Supabse Credentials
SUPABASE_URL=https://gtszuhmfpywqwdetoqqo.supabase.co
SUPABASE_KEY='sb_publishable_8Sxqgnn-VQJrVnpRy2WqUQ_g23PLPvk
